version: '3'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: catchreview
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql_data:/var/lib/mysql

  cr-api:
    build:
      context: .
    ports:
      - "8088:8088"
    depends_on:
      - mysql
    environment:
      DATABASE_URL: "root:1234@tcp(mysql:3306)/catchreview"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - cr-api

volumes:
  mysql_data: